# Generated by Django 5.0.3 on 2024-08-28 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='payment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('Orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order_tb')),
            ],
        ),
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Stock', models.BigIntegerField()),
                ('Categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category_tb')),
            ],
        ),
        migrations.CreateModel(
            name='orderdetails_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('Quantity', models.FloatField()),
                ('Status', models.CharField(max_length=100)),
                ('Orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order_tb')),
                ('Productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_tb')),
            ],
        ),
        migrations.CreateModel(
            name='retailer_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('PhoneNo', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='')),
                ('Loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_tb')),
            ],
        ),
        migrations.AddField(
            model_name='order_tb',
            name='Retailerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.retailer_tb'),
        ),
        migrations.CreateModel(
            name='return_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('Reason', models.CharField(max_length=100)),
                ('Orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order_tb')),
            ],
        ),
        migrations.CreateModel(
            name='staff_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('PhoneNo', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='')),
                ('Loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_tb')),
            ],
        ),
    ]
