# Generated by Django 5.1.1 on 2024-09-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='Image',
            field=models.FileField(default='sample.png', upload_to=''),
            preserve_default=False,
        ),
    ]
