# Generated by Django 5.1.1 on 2024-09-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_tb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='colour',
            field=models.CharField(default='red', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_tb',
            name='date',
            field=models.DateField(default='2024-09-29'),
            preserve_default=False,
        ),
    ]
