# Generated by Django 5.1.1 on 2024-09-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_tb_colour_product_tb_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_tb',
            name='colour',
        ),
    ]
