# Generated by Django 5.1.1 on 2024-09-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_product_tb_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_tb',
            name='date',
        ),
    ]
