# Generated by Django 5.1.1 on 2024-09-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_tb_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_tb',
            name='Colour',
        ),
    ]
