# Generated by Django 5.1.1 on 2024-09-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_product_tb_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='Colour',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
