# Generated by Django 5.1.1 on 2024-10-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product_tb_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_tb',
            name='Status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
