# Generated by Django 5.1.1 on 2024-10-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_staff_tb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_tb',
            name='Orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.orderdetails_tb'),
        ),
    ]
