
from django.contrib import admin
from django.urls import path, include

from myapp import views

urlpatterns = [
    path('',views.landing_page),
    path("login",views.login),
    path('login_post',views.login_post),
    path("register",views.register),
    path('admin_home',views.admin_home),
    path('admin_manage_staff',views.admin_manage_staff),
    path('block/<id>',views.block),
    path('unblock/<id>',views.unblock),
    path('add_staff',views.add_staff),
    path('add_staff_post',views.add_staff_post),
    path('edit_staff/<id>',views.edit_staff),
    path('edtcat/<id>',views.edtcat),
    path('dltcat/<id>',views.dltcat),
    path('edit_staff_post',views.edit_staff_post),
    path('about',views.about),
    path('contact',views.contact),
    path('manage_category',views.manage_category),
    path('add_category',views.add_category),
    path('addcat',views.addcat),
    path('updtcat',views.updtcat,name='updtcat'),
    path('forgot_password',views.forgot_password),
    path('forgot_password_post',views.forgot_password_post),
    path('popup',views.popup),
    path('staff_home',views.staff_home),
    path('user_reg',views.user_reg),
    path('retailer_home',views.retailer_home),
    path('verify',views.verify),
    path('sretailers',views.sretailers),
    path('acceptretailer/<id>',views.acceptretailer),
    path('rejectretailer/<id>',views.rejectretailer),
    path('viewretailers',views.viewretailers),
    path('staff_view_product',views.staff_view_product),
    path('staff_add_product',views.staff_add_product),
    path('add_product_post',views.add_product_post),
    path('edit_product_link/<id>',views.edit_product_link),
    path('edit_product_post',views.edit_product_post),
    path('staff_view_product_search',views.staff_view_product_search),
    path('checkemail',views.checkemail),
    path('checkusername',views.checkusername),
    path('orderproduct',views.orderproduct),
    path('add_to_cart/<id>', views.add_to_cart),
    path('deletecart/<id>', views.deletecart),
    path('user_pay_proceed/<id>/<amt>', views.user_pay_proceed),
    path('on_payment_success', views.on_payment_success),
    path('on_payment_failure', views.on_payment_failure),
    path('add_to_cart_post', views.add_to_cart_post),
    path('cart', views.cart),
    path('admin_view_product', views.admin_view_product),
    path('admin_view_product_search', views.admin_view_product_search),
    path('view_order', views.view_order),
    path('view_more_order/<id>', views.view_more_order),
    path('user_view_product_search', views.user_view_product_search),
    path('profile', views.profile),
    path('edit_profile', views.edit_profile),
    path('edit_profile_post', views.edit_profile_post),
    path('user_pay_proceed1', views.user_pay_proceed1),
    path('view_order1', views.view_order1),
    path('view_more_order1/<id>', views.view_more_order1),
    path('view_myorder_more/<id>', views.view_myorder_more),
    path('Return_product/<id>', views.Return_product),
    path('return_product_post', views.return_product_post),
    path('Admin_view_return_products', views.Admin_view_return_products),
    path('Admin_accept_retun_product/<id>', views.Admin_accept_retun_product),
    path('Admin_reject_retun_product/<id>', views.Admin_reject_retun_product),
    path('myorder', views.myorder),
    path('Staff_view_return_pr', views.Staff_view_return_pr),
    path('Retailer_view_retuen_info', views.Retailer_view_retuen_info),




]
